default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: basic-auth-development

test:
  <<: *default
  database: basic-auth-test

production:
  <<: *default
  database: basic-auth-production
  username: basic-auth
  password: <%= ENV['DATABASE_PASSWORD'] %>
